/**
 * TypeScript implementation of browser profile
 * Converted from browser_use/browser/profile.py
 */

import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs';
// Note: tmp module would need to be installed: npm install @types/tmp tmp
// For now, using a simple implementation
function createTempDir(prefix: string): { name: string; removeCallback: () => void } {
	const os = require('os');
	const path = require('path');
	const fs = require('fs');
	const tempDir = path.join(os.tmpdir(), `${prefix}${Math.random().toString(36).substring(2, 15)}`);
	fs.mkdirSync(tempDir, { recursive: true });
	return {
		name: tempDir,
		removeCallback: () => {
			try {
				fs.rmSync(tempDir, { recursive: true, force: true });
			} catch {
				// Ignore errors
			}
		},
	};
}
import type { CloudBrowserParams } from './cloud/views';

// Constants
export const CHROME_DEBUG_PORT = 9242; // use a non-default port to avoid conflicts with other tools / devs using 9222
export const DOMAIN_OPTIMIZATION_THRESHOLD = 100; // Convert domain lists to sets for O(1) lookup when >= this size

export const CHROME_DISABLED_COMPONENTS = [
	// Playwright defaults
	'AcceptCHFrame',
	'AutoExpandDetailsElement',
	'AvoidUnnecessaryBeforeUnloadCheckSync',
	'CertificateTransparencyComponentUpdater',
	'DestroyProfileOnBrowserClose',
	'DialMediaRouteProvider',
	'ExtensionManifestV2Disabled',
	'GlobalMediaControls',
	'HttpsUpgrades',
	'ImprovedCookieControls',
	'LazyFrameLoading',
	'LensOverlay',
	'MediaRouter',
	'PaintHolding',
	'ThirdPartyStoragePartitioning',
	'Translate',
	// Added by us:
	'AutomationControlled',
	'BackForwardCache',
	'OptimizationHints',
	'ProcessPerSiteUpToMainFrameThreshold',
	'InterestFeedContentSuggestions',
	'CalculateNativeWinOcclusion',
	'HeavyAdPrivacyMitigations',
	'PrivacySandboxSettings4',
	'AutofillServerCommunication',
	'CrashReporting',
	'OverscrollHistoryNavigation',
	'InfiniteSessionRestore',
	'ExtensionDisableUnsupportedDeveloper',
	'ExtensionManifestV2Unsupported',
];

export const CHROME_HEADLESS_ARGS = ['--headless=new'];

export const CHROME_DOCKER_ARGS = [
	'--no-sandbox',
	'--disable-gpu-sandbox',
	'--disable-setuid-sandbox',
	'--disable-dev-shm-usage',
	'--no-xshm',
	'--no-zygote',
	'--disable-site-isolation-trials',
];

export const CHROME_DISABLE_SECURITY_ARGS = [
	'--disable-site-isolation-trials',
	'--disable-web-security',
	'--disable-features=IsolateOrigins,site-per-process',
	'--allow-running-insecure-content',
	'--ignore-certificate-errors',
	'--ignore-ssl-errors',
	'--ignore-certificate-errors-spki-list',
];

export const CHROME_DETERMINISTIC_RENDERING_ARGS = [
	'--deterministic-mode',
	'--js-flags=--random-seed=1157259159',
	'--force-device-scale-factor=2',
	'--enable-webgl',
	'--font-render-hinting=none',
	'--force-color-profile=srgb',
];

export const CHROME_DEFAULT_ARGS = [
	'--disable-field-trial-config',
	'--disable-background-networking',
	'--disable-background-timer-throttling',
	'--disable-backgrounding-occluded-windows',
	'--disable-back-forward-cache',
	'--disable-breakpad',
	'--disable-client-side-phishing-detection',
	'--disable-component-extensions-with-background-pages',
	'--disable-component-update',
	'--no-default-browser-check',
	'--disable-dev-shm-usage',
	'--disable-hang-monitor',
	'--disable-ipc-flooding-protection',
	'--disable-popup-blocking',
	'--disable-prompt-on-repost',
	'--disable-renderer-backgrounding',
	'--metrics-recording-only',
	'--no-first-run',
	'--no-service-autorun',
	'--export-tagged-pdf',
	'--disable-search-engine-choice-screen',
	'--unsafely-disable-devtools-self-xss-warnings',
	'--enable-features=NetworkService,NetworkServiceInProcess',
	'--enable-network-information-downlink-max',
	'--test-type=gpu',
	'--disable-sync',
	'--allow-legacy-extension-manifests',
	'--allow-pre-commit-input',
	'--disable-blink-features=AutomationControlled',
	'--install-autogenerated-theme=0,0,0',
	'--log-level=2',
	'--disable-focus-on-load',
	'--disable-window-activation',
	'--generate-pdf-document-outline',
	'--no-pings',
	'--ash-no-nudges',
	'--disable-infobars',
	'--simulate-outdated-no-au="Tue, 31 Dec 2099 23:59:59 GMT"',
	'--hide-crash-restore-bubble',
	'--suppress-message-center-popups',
	'--disable-domain-reliability',
	'--disable-datasaver-prompt',
	'--disable-speech-synthesis-api',
	'--disable-speech-api',
	'--disable-print-preview',
	'--safebrowsing-disable-auto-update',
	'--disable-external-intent-requests',
	'--disable-desktop-notifications',
	'--noerrdialogs',
	'--silent-debugger-extension-api',
	'--disable-extensions-http-throttling',
	'--extensions-on-chrome-urls',
	'--disable-default-apps',
	`--disable-features=${CHROME_DISABLED_COMPONENTS.join(',')}`,
];

// Helper function
function _get_enable_default_extensions_default(): boolean {
	/**Get the default value for enable_default_extensions from env var or True.*/
	const env_val = process.env.BROWSER_USE_DISABLE_EXTENSIONS;
	if (env_val !== undefined) {
		// If DISABLE_EXTENSIONS is truthy, return False (extensions disabled)
		return !['0', 'false', 'no', 'off', ''].includes(env_val.toLowerCase());
	}
	return true;
}

// ===== ViewportSize =====

export interface ViewportSize {
	width: number;
	height: number;
}

// Helper to create ViewportSize
export function createViewportSize(width: number, height: number): ViewportSize {
	if (width < 0 || height < 0) {
		throw new Error('ViewportSize width and height must be >= 0');
	}
	return { width, height };
}

// Cache for display size
let _display_size_cache: ViewportSize | null = null;

export function get_display_size(): ViewportSize | null {
	// macOS - would need native bindings
	// Windows & Linux - would need screeninfo library
	// For now, return null and let the caller handle it
	// TODO: Implement platform-specific display size detection
	if (_display_size_cache) {
		return _display_size_cache;
	}

	// Try to get from environment or use default
	// In a real implementation, you'd use native modules or libraries
	_display_size_cache = { width: 1920, height: 1080 }; // Default fallback
	return _display_size_cache;
}

export function get_window_adjustments(): [number, number] {
	/**Returns recommended x, y offsets for window positioning*/
	const platform = os.platform();
	if (platform === 'darwin') {
		// macOS
		return [-4, 24]; // macOS has a small title bar, no border
	} else if (platform === 'win32') {
		// Windows
		return [-8, 0]; // Windows has a border on the left
	} else {
		// Linux
		return [0, 0];
	}
}

export function validate_url(url: string, schemes: string[] = []): string {
	/**Validate URL format and optionally check for specific schemes.*/
	try {
		const parsed_url = new URL(url);
		if (!parsed_url.hostname) {
			throw new Error(`Invalid URL format: ${url}`);
		}
		if (schemes.length > 0 && parsed_url.protocol && !schemes.includes(parsed_url.protocol.slice(0, -1))) {
			throw new Error(`URL has invalid scheme: ${url} (expected one of ${schemes.join(', ')})`);
		}
		return url;
	} catch (error: any) {
		if (error instanceof TypeError) {
			throw new Error(`Invalid URL format: ${url}`);
		}
		throw error;
	}
}

export function validate_float_range(value: number, min_val: number, max_val: number): number {
	/**Validate that float is within specified range.*/
	if (!(min_val <= value && value <= max_val)) {
		throw new Error(`Value ${value} outside of range ${min_val}-${max_val}`);
	}
	return value;
}

export function validate_cli_arg(arg: string): string {
	/**Validate that arg is a valid CLI argument.*/
	if (!arg.startsWith('--')) {
		throw new Error(
			`Invalid CLI argument: ${arg} (should start with --, e.g. --some-key="some value here")`
		);
	}
	return arg;
}

// ===== Enum definitions =====

export enum RecordHarContent {
	OMIT = 'omit',
	EMBED = 'embed',
	ATTACH = 'attach',
}

export enum RecordHarMode {
	FULL = 'full',
	MINIMAL = 'minimal',
}

export enum BrowserChannel {
	CHROMIUM = 'chromium',
	CHROME = 'chrome',
	CHROME_BETA = 'chrome-beta',
	CHROME_DEV = 'chrome-dev',
	CHROME_CANARY = 'chrome-canary',
	MSEDGE = 'msedge',
	MSEDGE_BETA = 'msedge-beta',
	MSEDGE_DEV = 'msedge-dev',
	MSEDGE_CANARY = 'msedge-canary',
}

// Using constants from central location in browser_use.config
export const BROWSERUSE_DEFAULT_CHANNEL = BrowserChannel.CHROMIUM;

// ===== Type definitions with validators =====

export type UrlStr = string; // Would use AfterValidator in Python
export type NonNegativeFloat = number; // Would use AfterValidator in Python
export type CliArgStr = string; // Would use AfterValidator in Python

// ===== Base Models =====

export interface BrowserContextArgs {
	/**
	 * Base model for common browser context parameters used by
	 * both BrowserType.new_context() and BrowserType.launch_persistent_context().
	 */
	accept_downloads?: boolean;
	permissions?: string[];
	user_agent?: string | null;
	screen?: ViewportSize | null;
	viewport?: ViewportSize | null;
	no_viewport?: boolean | null;
	device_scale_factor?: number | null;
	record_har_content?: RecordHarContent;
	record_har_mode?: RecordHarMode;
	record_har_path?: string | null;
	record_video_dir?: string | null;
}

export interface BrowserConnectArgs {
	/**
	 * Base model for common browser connect parameters used by
	 * both connect_over_cdp() and connect_over_ws().
	 */
	headers?: Record<string, string> | null;
}

export interface BrowserLaunchArgs {
	/**
	 * Base model for common browser launch parameters used by
	 * both launch() and launch_persistent_context().
	 */
	env?: Record<string, string | number | boolean> | null;
	executable_path?: string | null;
	headless?: boolean | null;
	args?: string[];
	ignore_default_args?: string[] | boolean;
	channel?: BrowserChannel | null;
	chromium_sandbox?: boolean;
	devtools?: boolean;
	downloads_path?: string | null;
	traces_dir?: string | null;
}

export interface BrowserNewContextArgs extends BrowserContextArgs {
	/**
	 * Pydantic model for new_context() arguments.
	 * Extends BaseContextParams with storage_state parameter.
	 */
	storage_state?: string | Record<string, any> | null;
}

export interface BrowserLaunchPersistentContextArgs extends BrowserLaunchArgs, BrowserContextArgs {
	/**
	 * Pydantic model for launch_persistent_context() arguments.
	 * Combines browser launch parameters and context parameters,
	 * plus adds the user_data_dir parameter.
	 */
	user_data_dir?: string | null;
}

export interface ProxySettings {
	/**Typed proxy settings for Chromium traffic.*/
	server?: string | null;
	bypass?: string | null;
	username?: string | null;
	password?: string | null;
}

/**
 * A BrowserProfile is a static template collection of kwargs that can be passed to:
 * 	- BrowserType.launch(**BrowserLaunchArgs)
 * 	- BrowserType.connect(**BrowserConnectArgs)
 * 	- BrowserType.connect_over_cdp(**BrowserConnectArgs)
 * 	- BrowserType.launch_persistent_context(**BrowserLaunchPersistentContextArgs)
 * 	- BrowserContext.new_context(**BrowserNewContextArgs)
 * 	- BrowserSession(**BrowserProfile)
 */
export class BrowserProfile
	implements BrowserConnectArgs, BrowserLaunchPersistentContextArgs, BrowserLaunchArgs, BrowserNewContextArgs
{
	// From BrowserConnectArgs
	headers?: Record<string, string> | null;

	// From BrowserLaunchArgs
	env?: Record<string, string | number | boolean> | null;
	executable_path?: string | null;
	headless?: boolean | null;
	args: string[] = [];
	ignore_default_args: string[] | boolean = [
		'--enable-automation',
		'--disable-extensions',
		'--hide-scrollbars',
		'--disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DeferRendererTasksAfterInput,DestroyProfileOnBrowserClose,DialMediaRouteProvider,ExtensionManifestV2Disabled,GlobalMediaControls,HttpsUpgrades,ImprovedCookieControls,LazyFrameLoading,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,Translate',
	];
	channel?: BrowserChannel | null = null;
	chromium_sandbox: boolean = true; // Would check CONFIG.IN_DOCKER
	devtools: boolean = false;
	downloads_path?: string | null = null;
	traces_dir?: string | null = null;

	// From BrowserContextArgs
	accept_downloads: boolean = true;
	permissions: string[] = ['clipboardReadWrite', 'notifications'];
	user_agent?: string | null = null;
	screen?: ViewportSize | null = null;
	viewport?: ViewportSize | null = null;
	no_viewport?: boolean | null = null;
	device_scale_factor?: number | null = null;
	record_har_content: RecordHarContent = RecordHarContent.EMBED;
	record_har_mode: RecordHarMode = RecordHarMode.FULL;
	record_har_path?: string | null = null;
	record_video_dir?: string | null = null;

	// From BrowserLaunchPersistentContextArgs
	user_data_dir?: string | null = null;

	// From BrowserNewContextArgs
	storage_state?: string | Record<string, any> | null = null;

	// Session/connection configuration
	cdp_url?: string | null = null;
	is_local: boolean = false;
	use_cloud: boolean = false;
	cloud_browser_params?: CloudBrowserParams | null = null;

	// Custom options
	disable_security: boolean = false;
	deterministic_rendering: boolean = false;
	allowed_domains?: string[] | Set<string> | null = null;
	prohibited_domains?: string[] | Set<string> | null = null;
	block_ip_addresses: boolean = false;
	keep_alive?: boolean | null = null;

	// Proxy settings
	proxy?: ProxySettings | null = null;
	enable_default_extensions: boolean = _get_enable_default_extensions_default();
	demo_mode: boolean = false;
	cookie_whitelist_domains: string[] = ['nature.com', 'qatarairways.com'];

	window_size?: ViewportSize | null = null;
	window_height?: number | null = null; // DEPRECATED
	window_width?: number | null = null; // DEPRECATED
	window_position: ViewportSize = { width: 0, height: 0 };
	cross_origin_iframes: boolean = true;
	max_iframes: number = 100;
	max_iframe_depth: number = 5;

	// Page load/wait timings
	minimum_wait_page_load_time: number = 0.25;
	wait_for_network_idle_page_load_time: number = 0.5;
	wait_between_actions: number = 0.1;

	// UI/viewport/DOM
	highlight_elements: boolean = true;
	dom_highlight_elements: boolean = false;
	filter_highlight_ids: boolean = true;
	paint_order_filtering: boolean = true;
	interaction_highlight_color: string = 'rgb(255, 127, 39)';
	interaction_highlight_duration: number = 1.0;

	// Downloads
	auto_download_pdfs: boolean = true;

	profile_directory: string = 'Default';

	record_video_size?: ViewportSize | null = null;
	record_video_framerate: number = 30;

	constructor(init?: Partial<BrowserProfile>) {
		if (init) {
			Object.assign(this, init);
		}
		// Run validators
		this.validate();
		this.detect_display_configuration();
		this._copy_profile();
	}

	get cloud_browser(): boolean {
		/**Alias for use_cloud field for compatibility.*/
		return this.use_cloud;
	}

	validate(): void {
		/**Run all validators.*/
		// Validate devtools and headless
		if (this.headless && this.devtools) {
			throw new Error('headless=True and devtools=True cannot both be set at the same time');
		}

		// Set default downloads path
		if (this.downloads_path === null || this.downloads_path === undefined) {
			const unique_id = Math.random().toString(36).substring(2, 10);
			this.downloads_path = `/tmp/browser-use-downloads-${unique_id}`;
			// Create directory
			if (!fs.existsSync(this.downloads_path)) {
				fs.mkdirSync(this.downloads_path, { recursive: true });
			}
		}

		// Optimize large domain lists
		if (this.allowed_domains && Array.isArray(this.allowed_domains) && this.allowed_domains.length >= DOMAIN_OPTIMIZATION_THRESHOLD) {
			console.warn(
				`🔧 Optimizing domain list with ${this.allowed_domains.length} items to set for O(1) lookup. ` +
					`Note: Pattern matching (*.domain.com, etc.) is not supported for lists >= ${DOMAIN_OPTIMIZATION_THRESHOLD} items. ` +
					`Use exact domains only or keep list size < ${DOMAIN_OPTIMIZATION_THRESHOLD} for pattern support.`
			);
			this.allowed_domains = new Set(this.allowed_domains);
		}

		if (this.prohibited_domains && Array.isArray(this.prohibited_domains) && this.prohibited_domains.length >= DOMAIN_OPTIMIZATION_THRESHOLD) {
			console.warn(
				`🔧 Optimizing domain list with ${this.prohibited_domains.length} items to set for O(1) lookup.`
			);
			this.prohibited_domains = new Set(this.prohibited_domains);
		}

		// Copy old config names to new
		if (this.window_width || this.window_height) {
			console.warn(
				`⚠️ BrowserProfile(window_width=..., window_height=...) are deprecated, use BrowserProfile(window_size={"width": 1920, "height": 1080}) instead.`
			);
			if (!this.window_size) {
				this.window_size = { width: 0, height: 0 };
			}
			this.window_size.width = this.window_size.width || this.window_width || 1920;
			this.window_size.height = this.window_size.height || this.window_height || 1080;
		}

		// Warn about storage_state and user_data_dir conflict
		const has_storage_state = this.storage_state !== null && this.storage_state !== undefined;
		const has_user_data_dir =
			this.user_data_dir !== null &&
			this.user_data_dir !== undefined &&
			!this.user_data_dir.toLowerCase().includes('tmp');

		if (has_storage_state && has_user_data_dir) {
			console.warn(
				`⚠️ BrowserSession(...) was passed both storage_state AND user_data_dir. storage_state=${this.storage_state} will forcibly overwrite ` +
					`cookies/localStorage/sessionStorage in user_data_dir=${this.user_data_dir}. ` +
					`For multiple browsers in parallel, use only storage_state with user_data_dir=None, ` +
					`or use a separate user_data_dir for each browser and set storage_state=None.`
			);
		}

		// Warn about deterministic rendering
		if (this.deterministic_rendering) {
			console.warn(
				'⚠️ BrowserSession(deterministic_rendering=True) is NOT RECOMMENDED. It breaks many sites and increases chances of getting blocked by anti-bot systems. ' +
					'It hardcodes the JS random seed and forces browsers across Linux/Mac/Windows to use the same font rendering engine so that identical screenshots can be generated.'
			);
		}

		// Validate proxy settings
		if (this.proxy && this.proxy.bypass && !this.proxy.server) {
			console.warn('BrowserProfile.proxy.bypass provided but proxy has no server; bypass will be ignored.');
		}

		// Validate highlight elements conflict
		if (this.highlight_elements && this.dom_highlight_elements) {
			console.warn(
				'⚠️ Both highlight_elements and dom_highlight_elements are enabled. ' +
					'dom_highlight_elements takes priority. Setting highlight_elements=False.'
			);
			this.highlight_elements = false;
		}
	}

	_copy_profile(): void {
		/**Copy profile to temp directory if user_data_dir is not None and not already a temp dir.*/
		if (!this.user_data_dir) {
			return;
		}

		const user_data_str = this.user_data_dir.toLowerCase();
		if (user_data_str.includes('browser-use-user-data-dir-')) {
			// Already using a temp directory, no need to copy
			return;
		}

		const is_chrome =
			user_data_str.includes('chrome') ||
			(this.executable_path && this.executable_path.toLowerCase().includes('chrome')) ||
			(this.channel &&
				[
					BrowserChannel.CHROME,
					BrowserChannel.CHROME_BETA,
					BrowserChannel.CHROME_DEV,
					BrowserChannel.CHROME_CANARY,
				].includes(this.channel));

		if (!is_chrome) {
			return;
		}

		// Create temp directory
		const temp_dir = createTempDir('browser-use-user-data-dir-');
		const path_original_user_data = path.resolve(this.user_data_dir);
		const path_original_profile = path.join(path_original_user_data, this.profile_directory);
		const path_temp_profile = path.join(temp_dir.name, this.profile_directory);

		if (fs.existsSync(path_original_profile)) {
			// Copy profile directory
			// Note: In TypeScript, we'd use fs-extra or similar for recursive copy
			// For now, we'll use a simple implementation
			try {
				fs.mkdirSync(path_temp_profile, { recursive: true });
				// TODO: Implement recursive directory copy
				// This would require fs-extra or similar library
				console.info(
					`Copied profile (${this.profile_directory}) and Local State to temp directory: ${temp_dir.name}`
				);
			} catch (error: any) {
				console.warn(`Failed to copy profile: ${error}`);
			}

			// Copy Local State file
			const local_state_src = path.join(path_original_user_data, 'Local State');
			const local_state_dst = path.join(temp_dir.name, 'Local State');
			if (fs.existsSync(local_state_src)) {
				try {
					fs.copyFileSync(local_state_src, local_state_dst);
				} catch (error: any) {
					console.warn(`Failed to copy Local State: ${error}`);
				}
			}
		} else {
			fs.mkdirSync(path_temp_profile, { recursive: true });
			console.info(`Created new profile (${this.profile_directory}) in temp directory: ${temp_dir.name}`);
		}

		this.user_data_dir = temp_dir.name;
	}

	get_args(): string[] {
		/**Get the list of all Chrome CLI launch args for this profile (compiled from defaults, user-provided, and system-specific).*/

		let default_args: string[];
		if (Array.isArray(this.ignore_default_args)) {
			default_args = CHROME_DEFAULT_ARGS.filter((arg) => !this.ignore_default_args.includes(arg));
		} else if (this.ignore_default_args === true) {
			default_args = [];
		} else {
			default_args = CHROME_DEFAULT_ARGS;
		}

		if (!this.user_data_dir) {
			throw new Error('user_data_dir must be set to a non-default path');
		}

		// Capture args before conversion for logging
		const pre_conversion_args: string[] = [
			...default_args,
			...this.args,
			`--user-data-dir=${this.user_data_dir}`,
			`--profile-directory=${this.profile_directory}`,
			...(process.env.IN_DOCKER === '1' || !this.chromium_sandbox ? CHROME_DOCKER_ARGS : []),
			...(this.headless ? CHROME_HEADLESS_ARGS : []),
			...(this.disable_security ? CHROME_DISABLE_SECURITY_ARGS : []),
			...(this.deterministic_rendering ? CHROME_DETERMINISTIC_RENDERING_ARGS : []),
			...(this.window_size
				? [`--window-size=${this.window_size.width},${this.window_size.height}`]
				: this.headless
					? []
					: ['--start-maximized']),
			...(this.window_position
				? [`--window-position=${this.window_position.width},${this.window_position.height}`]
				: []),
			...(this.enable_default_extensions ? this._get_extension_args() : []),
		];

		// Proxy flags
		if (this.proxy?.server) {
			pre_conversion_args.push(`--proxy-server=${this.proxy.server}`);
			if (this.proxy.bypass) {
				pre_conversion_args.push(`--proxy-bypass-list=${this.proxy.bypass}`);
			}
		}

		// User agent flag
		if (this.user_agent) {
			pre_conversion_args.push(`--user-agent=${this.user_agent}`);
		}

		// Special handling for --disable-features to merge values instead of overwriting
		const disable_features_values: string[] = [];
		const non_disable_features_args: string[] = [];

		// Extract and merge all --disable-features values
		for (const arg of pre_conversion_args) {
			if (arg.startsWith('--disable-features=')) {
				const features = arg.split('=', 2)[1];
				disable_features_values.push(...features.split(','));
			} else {
				non_disable_features_args.push(arg);
			}
		}

		// Remove duplicates while preserving order
		if (disable_features_values.length > 0) {
			const unique_features: string[] = [];
			const seen = new Set<string>();
			for (const feature of disable_features_values) {
				const trimmed = feature.trim();
				if (trimmed && !seen.has(trimmed)) {
					unique_features.push(trimmed);
					seen.add(trimmed);
				}
			}

			// Add merged disable-features back
			non_disable_features_args.push(`--disable-features=${unique_features.join(',')}`);
		}

		// Convert to dict and back to dedupe and merge other duplicate args
		const final_args_list = BrowserProfile.args_as_list(
			BrowserProfile.args_as_dict(non_disable_features_args)
		);

		return final_args_list;
	}

	_get_extension_args(): string[] {
		/**Get Chrome args for enabling default extensions (ad blocker and cookie handler).*/
		const extension_paths = this._ensure_default_extensions_downloaded();

		const args = [
			'--enable-extensions',
			'--disable-extensions-file-access-check',
			'--disable-extensions-http-throttling',
			'--enable-extension-activity-logging',
		];

		if (extension_paths.length > 0) {
			args.push(`--load-extension=${extension_paths.join(',')}`);
		}

		return args;
	}

	_ensure_default_extensions_downloaded(): string[] {
		/**
		 * Ensure default extensions are downloaded and cached locally.
		 * Returns list of paths to extension directories.
		 */
		// Extension definitions
		const extensions = [
			{
				name: 'uBlock Origin',
				id: 'cjpalhdlnbpafiamejdnhcphjbkeiagm',
				url: 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133&acceptformat=crx3&x=id%3Dcjpalhdlnbpafiamejdnhcphjbkeiagm%26uc',
			},
			{
				name: "I still don't care about cookies",
				id: 'edibdbjcniadpccecjdfdjjppcpchdlm',
				url: 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133&acceptformat=crx3&x=id%3Dedibdbjcniadpccecjdfdjjppcpchdlm%26uc',
			},
			{
				name: 'ClearURLs',
				id: 'lckanjgmijmafbedllaakclkaicjfmnk',
				url: 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133&acceptformat=crx3&x=id%3Dlckanjgmijmafbedllaakclkaicjfmnk%26uc',
			},
			{
				name: 'Force Background Tab',
				id: 'gidlfommnbibbmegmgajdbikelkdcmcl',
				url: 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133&acceptformat=crx3&x=id%3Dgidlfommnbibbmegmgajdbikelkdcmcl%26uc',
			},
		];

		// TODO: Implement extension downloading and extraction
		// This would require:
		// 1. HTTP client to download .crx files
		// 2. ZIP extraction library (adm-zip or similar)
		// 3. File system operations
		// For now, return empty array
		console.warn(
			'Extension downloading is not yet fully implemented in TypeScript. Please use the Python version for extension support.'
		);
		return [];
	}

	_apply_minimal_extension_patch(ext_dir: string, whitelist_domains: string[]): void {
		/**Minimal patch: pre-populate chrome.storage.local with configurable domain whitelist.*/
		// TODO: Implement extension patching
		// This would require reading and modifying JavaScript files
	}

	_download_extension(url: string, output_path: string): void {
		/**Download extension .crx file.*/
		// TODO: Implement using fetch API or axios
		throw new Error('Extension downloading not yet implemented in TypeScript');
	}

	_extract_extension(crx_path: string, extract_dir: string): void {
		/**Extract .crx file to directory.*/
		// TODO: Implement using adm-zip or similar
		throw new Error('Extension extraction not yet implemented in TypeScript');
	}

	detect_display_configuration(): void {
		/**
		 * Detect the system display size and initialize the display-related config defaults:
		 *         screen, window_size, window_position, viewport, no_viewport, device_scale_factor
		 */
		const display_size = get_display_size();
		const has_screen_available = display_size !== null;
		this.screen = this.screen || display_size || { width: 1920, height: 1080 };

		// if no headless preference specified, prefer headful if there is a display available
		if (this.headless === null || this.headless === undefined) {
			this.headless = !has_screen_available;
		}

		// Determine viewport behavior based on mode and user preferences
		const user_provided_viewport = this.viewport !== null && this.viewport !== undefined;

		if (this.headless) {
			// Headless mode: always use viewport for content size control
			this.viewport = this.viewport || this.window_size || this.screen;
			this.window_position = undefined;
			this.window_size = undefined;
			this.no_viewport = false;
		} else {
			// Headful mode: respect user's viewport preference
			this.window_size = this.window_size || this.screen;

			if (user_provided_viewport) {
				// User explicitly set viewport - enable viewport mode
				this.no_viewport = false;
			} else {
				// Default headful: content fits to window (no viewport)
				this.no_viewport = this.no_viewport === null || this.no_viewport === undefined ? true : this.no_viewport;
			}
		}

		// Handle special requirements (device_scale_factor forces viewport mode)
		if (this.device_scale_factor && (this.no_viewport === null || this.no_viewport === undefined)) {
			this.no_viewport = false;
		}

		// Finalize configuration
		if (this.no_viewport) {
			// No viewport mode: content adapts to window
			this.viewport = undefined;
			this.device_scale_factor = undefined;
			this.screen = undefined;
		} else {
			// Viewport mode: ensure viewport is set
			this.viewport = this.viewport || this.screen;
			this.device_scale_factor = this.device_scale_factor || 1.0;
		}

		if (this.headless && this.no_viewport) {
			throw new Error('headless=True and no_viewport=True cannot both be set at the same time');
		}
	}

	static args_as_dict(args: string[]): Record<string, string> {
		/**Return the extra launch CLI args as a dictionary.*/
		const args_dict: Record<string, string> = {};
		for (const arg of args) {
			const parts = arg.split('=', 2);
			const key = parts[0].trim().replace(/^--/, '');
			const value = parts.length > 1 ? parts[1].trim() : '';
			args_dict[key] = value;
		}
		return args_dict;
	}

	static args_as_list(args: Record<string, string>): string[] {
		/**Return the extra launch CLI args as a list of strings.*/
		return Object.entries(args).map(([key, value]) => {
			const clean_key = key.replace(/^--/, '');
			return value ? `--${clean_key}=${value}` : `--${clean_key}`;
		});
	}
}
