/**
 * This implementation is based on the OpenAI types, while removing all the parts that are not needed for Browser Use.
 */

// ============================================================================
// Utility Functions
// ============================================================================

function _truncate(text: string, maxLength: number = 50): string {
	/**Truncate text to max_length characters, adding ellipsis if truncated.*/
	if (text.length <= maxLength) {
		return text;
	}
	return text.substring(0, maxLength - 3) + '...';
}

function _formatImageUrl(url: string, maxLength: number = 50): string {
	/**Format image URL for display, truncating if necessary.*/
	if (url.startsWith('data:')) {
		// Base64 image
		const mediaType = url.includes(';') ? url.split(';')[0].split(':')[1] : 'image';
		return `<base64 ${mediaType}>`;
	} else {
		// Regular URL
		return _truncate(url, maxLength);
	}
}

// ============================================================================
// Content Part Types
// ============================================================================

export type SupportedImageMediaType = 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp';

export type ContentPartTextParam = {
	text: string;
	type: 'text';
};

export type ContentPartRefusalParam = {
	refusal: string;
	type: 'refusal';
};

export type ImageURL = {
	url: string;
	/**Either a URL of the image or the base64 encoded image data.*/
	detail?: 'auto' | 'low' | 'high';
	/**Specifies the detail level of the image.
    Learn more in the
    [Vision guide](https://platform.openai.com/docs/guides/vision#low-or-high-fidelity-image-understanding).
    */
	media_type?: SupportedImageMediaType;
	/**needed for Anthropic*/
};

export type ContentPartImageParam = {
	image_url: ImageURL;
	type: 'image_url';
};

export type Function = {
	arguments: string;
	/**The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    */
	name: string;
	/**The name of the function to call.*/
};

export type ToolCall = {
	id: string;
	/**The ID of the tool call.*/
	function: Function;
	/**The function that the model called.*/
	type: 'function';
	/**The type of the tool. Currently, only `function` is supported.*/
};

// ============================================================================
// Message Types
// ============================================================================

export type _MessageBase = {
	role: 'user' | 'system' | 'assistant';
	cache?: boolean;
	/**Whether to cache this message. This is only applicable when using Anthropic models.*/
};

export type UserMessage = _MessageBase & {
	role: 'user';
	/**The role of the messages author, in this case `user`.*/
	content: string | (ContentPartTextParam | ContentPartImageParam)[];
	/**The contents of the user message.*/
	name?: string | null;
	/**An optional name for the participant.
    Provides the model information to differentiate between participants of the same
    role.
    */
};

export type SystemMessage = _MessageBase & {
	role: 'system';
	/**The role of the messages author, in this case `system`.*/
	content: string | ContentPartTextParam[];
	/**The contents of the system message.*/
	name?: string | null;
};

export type AssistantMessage = _MessageBase & {
	role: 'assistant';
	/**The role of the messages author, in this case `assistant`.*/
	content: string | (ContentPartTextParam | ContentPartRefusalParam)[] | null;
	/**The contents of the assistant message.*/
	name?: string | null;
	refusal?: string | null;
	/**The refusal message by the assistant.*/
	tool_calls?: ToolCall[];
	/**The tool calls generated by the model, such as function calls.*/
};

export type BaseMessage = UserMessage | SystemMessage | AssistantMessage;

// ============================================================================
// Helper Functions for Message Types
// ============================================================================

/**
 * Get text content from a UserMessage
 */
export function getUserMessageText(message: UserMessage): string {
	if (typeof message.content === 'string') {
		return message.content;
	} else if (Array.isArray(message.content)) {
		return message.content
			.filter((part) => part.type === 'text')
			.map((part) => part.text)
			.join('\n');
	}
	return '';
}

/**
 * Get text content from a SystemMessage
 */
export function getSystemMessageText(message: SystemMessage): string {
	if (typeof message.content === 'string') {
		return message.content;
	} else if (Array.isArray(message.content)) {
		return message.content
			.filter((part) => part.type === 'text')
			.map((part) => part.text)
			.join('\n');
	}
	return '';
}

/**
 * Get text content from an AssistantMessage
 */
export function getAssistantMessageText(message: AssistantMessage): string {
	if (message.content === null || message.content === undefined) {
		return '';
	}
	if (typeof message.content === 'string') {
		return message.content;
	} else if (Array.isArray(message.content)) {
		let text = '';
		for (const part of message.content) {
			if (part.type === 'text') {
				text += part.text;
			} else if (part.type === 'refusal') {
				text += `[Refusal] ${part.refusal}`;
			}
		}
		return text;
	}
	return '';
}
